
[tools]
aws-cli = { version = "latest", symlink_bins = "true" }
"github:floci-io/floci-cli" = "latest"
kubectl = "latest"
minikube = "latest"

#______________________________________________________________________________

[shell_alias]

# SUB_SECTION: Docker
d-containers = "mise d-containers"
d-images = "mise d-images"
d-ports = "mise d-ports"
d-status = "mise d-docker-status"
d-toggle = "mise d-toggle"
d-volumes = "mise d-volumes"
d-tidy = "mise d-tidy"

# SUB_SECTION: Kubernetes
k8 = "mise k8"

# SUB_SECTION: Minikube
mk-start = "mise mk-start"
mk-stop = "mise mk-stop"
mk-delete = "mise mk-delete"
#______________________________________________________________________________
